Changing CI explanation
r-devel/rdevguide pull request #233
Opened 2024-12-06 10:29 UTC by ccamara

### Summary

Readme states that CI is done using travis CI, and this is an outdated info. This minor, trivial, PR explains that we are using github actions instead.

### What should a reviewer concentrate their feedback on?

- [ ] CI instructions are accurate and up-to-date.

### Acknowledging contributors

- [ ] All contributors to this pull request are already named in the [table of contributors](https://github.com/r-devel/rdevguide/blob/main/README.md#contributors-) in the README file.
- [x] The following people should be added to the [table of contributors](https://github.com/r-devel/rdevguide/blob/main/README.md#contributors-) in the README file:  ccamara
- [ ] Use the [How to acknowledge contributors](https://github.com/r-devel/rdevguide/blob/main/HOWTO-acknowledge-contributors.md) to add new contributor(s) using the [All Contributors](https://allcontributors.org/) Bot.

2024-12-06 10:43 UTC, llrs approved these changes

2024-12-06 15:50 UTC, hturner requested changes
Thanks @ccamara, I corrected some of the technical details

2024-12-06 15:50 UTC, hturner commented on README.md
> +Deployment is done via GitHub Actions (as defined [here](https://github.com/r-devel/rdevguide/tree/main/.github/workflows)):
```suggestion
Deployment is done via GitHub Actions, as specified in the [publish.yml](https://github.com/r-devel/rdevguide/blob/main/.github/workflows/publish.yml) workflow:
```

2024-12-06 15:50 UTC, hturner commented on README.md
>  - whenever there's a push to main, the book is built and its content is put in the `docs` directory.
```suggestion
- whenever there's a push to main, the book is built and its content is put on the `gh-pages` branch, triggering the github-pages bot to deploy to <https://contributor.r-project.org/rdevguide/> .
```

2024-12-11 08:43 UTC, hturner commented
@all-contributors please add @ccamara for documentation

2024-12-11 08:43 UTC, hturner approved these changes

2024-12-11 08:44 UTC, merged